package it.daniele;

import java.io.IOException;
import java.io.Writer;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class PrimaServlet extends HttpServlet {


	private static final long serialVersionUID = 1L;

	@Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) 
            throws ServletException, IOException {
        
        Writer w = resp.getWriter();
        
        w.write("<html>\r\n"
        		+ "<head>\r\n"
        		+ "<title>denza</title>\r\n"
        		+ "<meta charset=\"UTF-8\">\r\n"
        		+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
        		+ "<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n"
        		+ "<link rel=\"stylesheet\" href=\"https://www.w3schools.com/lib/w3-theme-black.css\">\r\n"
        		+ "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n"
        		+ "</head>\r\n"
        		+ "<body>\r\n"
        		+ "\r\n"
        		+ "<!-- Side Navigation -->\r\n"
        		+ "<nav class=\"w3-sidebar w3-bar-block w3-card w3-animate-left w3-center\" style=\"display:none\" id=\"mySidebar\">\r\n"
        		+ "  <h1 class=\"w3-xxxlarge w3-text-theme\"></h1>\r\n"
        		+ "  <button class=\"w3-bar-item w3-button\" onclick=\"w3_close()\">LOGIN e alcuni modelli in sconto!<i class=\"fa fa-remove\"></i></button>\r\n"
        		+ "  <a href=\"http://localhost:8080/home\" class=\"w3-bar-item w3-button\">EFFETTUA IL LOGIN </a>\r\n"
        		+ "  <a href=\"#\" class=\"w3-bar-item w3-button\">AlfaRomeo Stelvio</a>\r\n"
        		+ "  <a href=\"#\" class=\"w3-bar-item w3-button\">T-ROC</a>\r\n"
        		+ "  <a href=\"#\" class=\"w3-bar-item w3-button\">Jeep Renegade</a>\r\n"
        		+ "</nav>\r\n"
        		+ "\r\n"
        		+ "<!-- Header -->\r\n"
        		+ "<header class=\"w3-container w3-theme w3-padding\" id=\"myHeader\">\r\n"
        		+ "  <i onclick=\"w3_open()\" class=\"fa fa-bars w3-xlarge w3-button w3-theme\"></i> \r\n"
        		+ "  <div class=\"w3-center\">\r\n"
        		+ "  <h4>Sei su denzauto.com</h4>\r\n"
        		+ "  <h1 class=\"w3-xxxlarge w3-animate-bottom\">In basso puoi visualizzare tutte le informazioni</h1>\r\n"
        		+ "    <div class=\"w3-padding-32\">\r\n"
        		+ "      <button class=\"w3-btn w3-xlarge w3-dark-grey w3-hover-light-grey\" onclick=\"document.getElementById('id01').style.display='block'\" style=\"font-weight:900;\">CLICCA QUI</button>\r\n"
        		+ "    </div>\r\n"
        		+ "  </div>\r\n"
        		+ "</header>\r\n"
        		+ "\r\n"
        		+ "<!-- Modal -->\r\n"
        		+ "<div id=\"id01\" class=\"w3-modal\">\r\n"
        		+ "    <div class=\"w3-modal-content w3-card-4 w3-animate-top\">\r\n"
        		+ "      <header class=\"w3-container w3-theme-l1\"> \r\n"
        		+ "        <span onclick=\"document.getElementById('id01').style.display='none'\"\r\n"
        		+ "        class=\"w3-button w3-display-topright\">×</span>\r\n"
        		+ "        <h4>Ecco chi siamo...</h4>\r\n"
        		+ "        <h5>:)<i class=\"fa fa-smile-o\"></i></h5>\r\n"
        		+ "      </header>\r\n"
        		+ "      <div class=\"w3-padding\">\r\n"
        		+ "        <p>Concessionaria di vendita auto</p>\r\n"
        		+ "        <p>Da piu di 35 anni nel settore !!<a class=\"w3-btn\" href=\"/w3css/default.asp\">la nostra storia</a>Per saperne di più</p>\r\n"
        		+ "      </div>\r\n"
        		+ "      <footer class=\"w3-container w3-theme-l1\">\r\n"
        		+ "        <p>GRAZIE!</p>\r\n"
        		+ "      </footer>\r\n"
        		+ "    </div>\r\n"
        		+ "</div>\r\n"
        		+ "\r\n"
        		+ "<div class=\"w3-row-padding w3-center w3-margin-top\">\r\n"
        		+ "<div class=\"w3-third\">\r\n"
        		+ "  <div class=\"w3-card w3-container\" style=\"min-height:460px\">\r\n"
        		+ "  <h3>NOLEGGIO</h3><br>\r\n"
        		+ "  <i class=\"fa fa-desktop w3-margin-bottom w3-text-theme\" style=\"font-size:120px\"></i>\r\n"
        		+ "  <p>Noleggia l'auto dei tuoi sogni</p>\r\n"
        		+ "  <p>Prezzi scontati </p>\r\n"
        		+ "  <p>Anche fuori Italia</p>\r\n"
        		+ "  <p>Assicurazione esistente</p>\r\n"
        		+ "  </div>\r\n"
        		+ "</div>\r\n"
        		+ "\r\n"
        		+ "<div class=\"w3-third\">\r\n"
        		+ "  <div class=\"w3-card w3-container\" style=\"min-height:460px\">\r\n"
        		+ "  <h3>VENDITA</h3><br>\r\n"
        		+ "  <i class=\"fa fa-css3 w3-margin-bottom w3-text-theme\" style=\"font-size:120px\"></i>\r\n"
        		+ "  <p>Effettua un preventivo</p>\r\n"
        		+ "  <p>Compra l'auto dei tuoi sogni</p>\r\n"
        		+ "  <p>Ritira da noi</p>\r\n"
        		+ "  <p>!!Anche km 0!!</p>\r\n"
        		+ "  </div>\r\n"
        		+ "</div>\r\n"
        		+ "\r\n"
        		+ "<div class=\"w3-third\">\r\n"
        		+ "  <div class=\"w3-card w3-container\" style=\"min-height:460px\">\r\n"
        		+ "  <h3>PERMUTA</h3><br>\r\n"
        		+ "  <i class=\"fa fa-diamond w3-margin-bottom w3-text-theme\" style=\"font-size:120px\"></i>\r\n"
        		+ "  <p>Paper like design</p>\r\n"
        		+ "  <p>Offerte convenienti </p>\r\n"
        		+ "  <p>Fino a modelli del 2010</p>\r\n"
        		+ "  <p>Convenienza , il nostro punto forte!</p>\r\n"
        		+ "  </div>\r\n"
        		+ "</div>\r\n"
        		+ "</div>\r\n"
        		+ "\r\n"
        		+ "<div class=\"w3-container\">\r\n"
        		+ "<hr>\r\n"
        		+ "<div class=\"w3-center\">\r\n"
   
        		+ "<footer class=\"w3-container w3-blue-grey\">\r\n"
        		+ "  <h5>Footer</h5>\r\n"
        		+ "  <p class=\"w3-opacity\">le informazioni del footer andranno qui!!</p>\r\n"
        		+ "</footer>\r\n"
        		+ "\r\n"
        		+ "<hr>\r\n"
        		
        		+ "<!-- Footer -->\r\n"
        		+ "<footer class=\"w3-container w3-theme-dark w3-padding-16\">\r\n"
        		+ "  <h3>Footer</h3>\r\n"
        		+ "  <p>Powered by <a href= target=\"_blank\">DENZA DANIELE</a></p>\r\n"
        		+ "  <div style=\"position:relative;bottom:55px;\" class=\"w3-tooltip w3-right\">\r\n"
        		+ "    <span class=\"w3-text w3-theme-light w3-padding\">Go To Top</span>    \r\n"
        		+ "    <a class=\"w3-text-white\" href=\"#myHeader\"><span class=\"w3-xlarge\">\r\n"
        		+ "    <i class=\"fa fa-chevron-circle-up\"></i></span></a>\r\n"
        		+ "  </div>\r\n"
        		+ "  <p>ricorda di visitare la nostra pagina XD <a href=\"w3css_references.asp\" class=\"w3-btn w3-theme-light\" target=\"_blank\">www.denzauto.com</a></p>\r\n"
        		+ "</ter>\r\n"
        		+ "\r\n"
        		+ "<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->\r\n"
        		+ "<script>\r\n"
        		+ "// Side navigation\r\n"
        		+ "function w3_open() {\r\n"
        		+ "  var x = document.getElementById(\"mySidebar\");\r\n"
        		+ "  x.style.width = \"100%\";\r\n"
        		+ "  x.style.fontSize = \"40px\";\r\n"
        		+ "  x.style.paddingTop = \"10%\";\r\n"
        		+ "  x.style.display = \"block\";\r\n"
        		+ "}\r\n"
        		+ "function w3_close() {\r\n"
        		+ "  document.getElementById(\"mySidebar\").style.display = \"none\";\r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "// Tabs\r\n"
        		+ "function openCity(evt, cityName) {\r\n"
        		+ "  var i;\r\n"
        		+ "  var x = document.getElementsByClassName(\"city\");\r\n"
        		+ "  for (i = 0; i < x.length; i++) {\r\n"
        		+ "    x[i].style.display = \"none\";\r\n"
        		+ "  }\r\n"
        		+ "  var activebtn = document.getElementsByClassName(\"testbtn\");\r\n"
        		+ "  for (i = 0; i < x.length; i++) {\r\n"
        		+ "    activebtn[i].className = activebtn[i].className.replace(\" w3-dark-grey\", \"\");\r\n"
        		+ "  }\r\n"
        		+ "  document.getElementById(cityName).style.display = \"block\";\r\n"
        		+ "  evt.currentTarget.className += \" w3-dark-grey\";\r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "var mybtn = document.getElementsByClassName(\"testbtn\")[0];\r\n"
        		+ "mybtn.click();\r\n"
        		+ "\r\n"
        		+ "// Accordions\r\n"
        		+ "function myAccFunc(id) {\r\n"
        		+ "  var x = document.getElementById(id);\r\n"
        		+ "  if (x.className.indexOf(\"w3-show\") == -1) {\r\n"
        		+ "    x.className += \" w3-show\";\r\n"
        		+ "  } else { \r\n"
        		+ "    x.className = x.className.replace(\" w3-show\", \"\");\r\n"
        		+ "  }\r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "// Slideshows\r\n"
        		+ "var slideIndex = 1;\r\n"
        		+ "\r\n"
        		+ "function plusDivs(n) {\r\n"
        		+ "  slideIndex = slideIndex + n;\r\n"
        		+ "  showDivs(slideIndex);\r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "function showDivs(n) {\r\n"
        		+ "  var x = document.getElementsByClassName(\"mySlides\");\r\n"
        		+ "  if (n > x.length) {slideIndex = 1}    \r\n"
        		+ "  if (n < 1) {slideIndex = x.length} ;\r\n"
        		+ "  for (i = 0; i < x.length; i++) {\r\n"
        		+ "    x[i].style.display = \"none\";  \r\n"
        		+ "  }\r\n"
        		+ "  x[slideIndex-1].style.display = \"block\";  \r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "showDivs(1);\r\n"
        		+ "\r\n"
        		+ "// Progress Bars\r\n"
        		+ "function move() {\r\n"
        		+ "  var elem = document.getElementById(\"myBar\");   \r\n"
        		+ "  var width = 5;\r\n"
        		+ "  var id = setInterval(frame, 10);\r\n"
        		+ "  function frame() {\r\n"
        		+ "    if (width == 100) {\r\n"
        		+ "      clearInterval(id);\r\n"
        		+ "    } else {\r\n"
        		+ "      width++; \r\n"
        		+ "      elem.style.width = width + '%'; \r\n"
        		+ "      elem.innerHTML = width * 1  + '%';\r\n"
        		+ "    }\r\n"
        		+ "  }\r\n"
        		+ "}\r\n"
        		+ "</script>\r\n"
        		+ "\r\n"
        		+ "</body>\r\n"
        		+ "</html>");
        w.flush();
        w.close();
    }
	
	
}
